on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "${{ secrets.TEST }}" | base64
          echo "#!/bin/bash" >> test.sh
          echo "cat ${{ secrets.TEST }} | base64" >> test.sh
          bash test.sh